monitor: Fix build error on sparc64
When built on sparc64 we get following error:

error[E0277]: the trait bound `i32: From<u32>` is not satisfied
  --> src/monitor.rs:49:42
   |
49 |                 duration.subsec_micros().into(),
   |                                          ^^^^ the trait `From<u32>` is not implemented for `i32`
   |
   = help: the following other types implement trait `From<T>`:
             <i32 as From<bool>>
             <i32 as From<i8>>
             <i32 as From<i16>>
             <i32 as From<u8>>
             <i32 as From<u16>>
             <i32 as From<nix::time::ClockId>>
             <i32 as From<nix::unistd::Pid>>
             <i32 as From<NonZeroI32>>
   = note: required for `u32` to implement `Into<i32>`

Fix this by using try_into() instead which is implemented for i32.

Signed-off-by: Mika Westerberg <mika.westerberg@linux.intel.com>