trace: Fix build error on sparc64
On sparc64 we get following error:

error[E0308]: mismatched types
   --> src/trace.rs:775:36
    |
775 |         Some(TimeVal::new(seconds, useconds))
    |              ------------          ^^^^^^^^ expected `i32`, found `i64`
    |              |
    |              arguments to this function are incorrect
    |

This is because suseconds_t is different on sparc64. Instead of using
i64 as the type, use suseconds_t. This should be correct on all
architectures.

Signed-off-by: Mika Westerberg <mika.westerberg@linux.intel.com>