util: Fix build error on i386
When doing 32-bit build we get following error:

error[E0308]: mismatched types
   --> src/util.rs:157:40
    |
157 |                 return Ok(TimeVal::new(seconds, 0));
    |                           ------------ ^^^^^^^ expected `i32`, found `i64`
    |                           |
    |                           arguments to this function are incorrect
    |

This is because time_t is 32-bit in i386. Fix this by using time_t
instead.

Signed-off-by: Mika Westerberg <mika.westerberg@linux.intel.com>